[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_SUPABASE_URL = "https://your-project-id.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key-here"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/jobs/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/category/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/location/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/companies"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200