[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/jobs/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/category/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/location/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/companies"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200