[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_SUPABASE_URL = "https://fywznswzldmccircvzic.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5d3puc3d6bGRtY2NpcmN2emljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTUzNTYsImV4cCI6MjA3MjYzMTM1Nn0.xvHjkl1RIsYsfaPqkdrG2pi9SdwHt9PwM8oO_Y9Cu4A"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/jobs/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/category/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/location/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/companies"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200